In [1]:
#import necessary package
import pandas as pd
import featuretools as ft

In [2]:
df = pd.read_csv("cleanedloans.csv",header=0,encoding='utf-8')

In [3]:
# Make an entityset and add the entity
es = ft.EntitySet(id = 'data')
es.entity_from_dataframe(entity_id = 'data', dataframe = df, 
                         make_index = True, index = 'index')

Entityset: data
  Entities:
    data [Rows: 576839, Columns: 60]
  Relationships:
    No relationships

In [4]:
# Run deep feature synthesis with transformation primitives
feature_matrix, feature_defs = ft.dfs(entityset = es, target_entity = 'data',
                                      trans_primitives = ['absolute','percentile'])

feature_matrix.head()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,grade,sub_grade,emp_length,annual_inc,...,PERCENTILE(ABSOLUTE(purpose_major_purchase)),PERCENTILE(ABSOLUTE(purpose_medical)),PERCENTILE(ABSOLUTE(purpose_moving)),PERCENTILE(ABSOLUTE(purpose_other)),PERCENTILE(ABSOLUTE(purpose_renewable_energy)),PERCENTILE(ABSOLUTE(purpose_small_business)),PERCENTILE(ABSOLUTE(purpose_vacation)),PERCENTILE(ABSOLUTE(purpose_wedding)),PERCENTILE(ABSOLUTE(term_ 36 months)),PERCENTILE(ABSOLUTE(term_ 60 months))
index,,,,,,,,,,,,,,,,,,,,,
0,12000897,27050.0,27050.0,27050.0,10.99,885.46,2,B2,10,55000.0,...,0.491554,0.495698,0.497389,0.478437,0.499763,0.495729,0.497582,0.499769,0.667762,0.33224
1,12011200,9750.0,9750.0,9750.0,13.98,333.14,3,C1,1,26000.0,...,0.491554,0.495698,0.497389,0.478437,0.499763,0.495729,0.497582,0.499769,0.667762,0.33224
2,1319523,12000.0,12000.0,12000.0,6.62,368.45,1,A2,10,105000.0,...,0.491554,0.495698,0.497389,0.478437,0.499763,0.495729,0.497582,0.499769,0.667762,0.33224
3,12011167,15000.0,15000.0,15000.0,8.90,476.30,1,A5,2,63000.0,...,0.491554,0.495698,0.497389,0.478437,0.499763,0.495729,0.497582,0.499769,0.667762,0.33224
4,11971241,12000.0,12000.0,12000.0,11.99,398.52,2,B3,10,130000.0,...,0.491554,0.495698,0.497389,0.478437,0.499763,0.495729,0.497582,0.499769,0.667762,0.33224

In [ ]:
feature_matrix.to_csv('featuretool.csv')